export const MAKE_PROPOSAL = "MAKE_PROPOSAL";
export const NOT_NEED_PROPOSAL = "NOT_NEED_PROPOSAL";
export const CHECK_PROPOSAL_NEED = "CHECK_PROPOSAL_NEED";
export const PROPOSAL_ACCEPTED = "PROPOSAL_ACCEPTED";

export const GET_CURRENT_ACCOUNT_REQUEST = "GET_CURRENT_ACCOUNT_REQUEST";
export const GET_CURRENT_ACCOUNT_RESPONSE = "GET_CURRENT_ACCOUNT_RESPONSE";

export const GET_SESSION_TOKEN_REQUEST = "GET_SESSION_TOKEN_REQUEST";
export const GET_SESSION_TOKEN_RESPONSE = "GET_SESSION_TOKEN_RESPONSE";

export const CREATE_SESSION_REQUEST = "CREATE_SESSION_REQUEST";
export const CREATE_SESSION_RESPONSE = "CREATE_SESSION_RESPONSE";

export const GET_VAULT_ITEMS_REQUEST = "GET_ITEMS_REQUEST";
export const GET_VAULT_ITEMS_RESPONSE = "GET_ITEMS_RESPONSE";

export const GET_VAULT_ITEM_REQUEST = "GET_ITEM_REQUEST";
export const GET_VAULT_ITEM_RESPONSE = "GET_ITEM_RESPONSE";

export const GET_SUGGESTIONS_REQUEST = "GET_SUGGESTIONS_REQUEST";
export const GET_SUGGESTIONS_RESPONSE = "GET_SUGGESTIONS_RESPONSE";

export const ERROR = "ERROR";

export const LOCK_UP = "LOCK_UP";

export const COLLECT_PAGE_DETAILS_REQUEST = "COLLECT_PAGE_DETAILS_REQUEST";
export const COLLECT_PAGE_DETAILS_RESPONSE = "COLLECT_PAGE_DETAILS_RESPONSE";

export const FILL_FORM = "FILL_FORM";
export const OPEN_AND_FILL_FORM = "OPEN_AND_FILL_FORM";

export const LOCK_APP = "LOCK_APP";
