export const SET_CURRENT_VAULT_ITEM_UUID = "SET_CURRENT_VAULT_ITEM_UUID";

export const GET_VAULT_ITEM = "GET_VAULT_ITEM";
export const GET_VAULT_ITEMS = "GET_VAULT_ITEMS";

export const GET_SUGGESTION = "GET_SUGGESTION";
export const GET_SUGGESTIONS = "GET_SUGGESTIONS";

export const SET_SEARCH_QUERY = "SET_SEARCH_QUERY";

export const CLEAR = "CLEAR";
