export const SET_CURRENT_VAULT_ITEM_UUID = "SET_CURRENT_VAULT_ITEM_UUID";

export const SET_VAULT_ITEMS = "SET_VAULT_ITEMS";
export const GET_VAULT_ITEMS = "GET_VAULT_ITEMS";

export const SET_VAULT_ITEM = "SET_VAULT_ITEM";
export const GET_VAULT_ITEM = "GET_VAULT_ITEM";

export const SET_SUGGESTIONS = "SET_SUGGESTIONS";
export const GET_SUGGESTIONS = "GET_SUGGESTIONS";
