export const SET_FETCH_STATUS = "SET_FETCH_STATUS";

export const SET_VAULT_ITEM = "SET_VAULT_ITEM";
export const SET_CURRENT_VAULT_ITEM_UUID = "SET_CURRENT_VAULT_ITEM_UUID";
export const CLEAR_VAULT_ITEM_LIST = "CLEAR_VAULT_ITEM_LIST";
