export const SET_VAULT_ITEM = "SET_VAULT_ITEM";
export const SET_SUGGESTION = "SET_SUGGESTION";

export const SET_CURRENT_VAULT_ITEM_UUID = "SET_CURRENT_VAULT_ITEM_UUID";

export const CLEAR_VAULT_ITEM_LIST = "CLEAR_VAULT_ITEM_LIST";
export const CLEAR_SUGGESTION_LIST = "CLEAR_SUGGESTION_LIST";

export const SET_SEARCH_QUERY = "SET_SEARCH_QUERY";
